### ISSUE TITLE
Doesn't work as expected.

### ISSUE THREAD

**Issue by trusktr** [lipp/doclets#123] opened 2016-05-16 00:02 UTC
For example, see these generated docs: https://doclets.io/trusktr/awaitbox/master

Then, look in the `src` folder of the repo: https://github.com/trusktr/awaitbox

Any tips on what to do?

**Comment by lipp** [comment] 2016-05-17 07:03
@trusktr The problem is mainly that JSDoc (which is used internally) has some difficulties to deduce proper types and names for ES6. 

For instance:
```
/**
 * Await for a certain amount of time.
 *
 * @example
 * ```js
 * async function main() {
 *     await sleep(10000)
 *     console.log('Logged after 10000 milliseconds!')
 * }
 * main()
 * ```
 */
export default
function sleep(duration) {
```
from https://github.com/trusktr/awaitbox/blob/master/src/timers/sleep.js

should be

```js
/**
 * Await for a certain amount of time.
 * @name sleep
 * @type function
 * @param {number} duration The time in ms to sleep
 * @returns {Promise} A promise which gets resolved after `duration` has expired.
 * @example
 * async function main() {
 *     await sleep(10000)
 *     console.log('Logged after 10000 milliseconds!')
 * }
 * main()
 */
export default
function sleep(duration) {
```

This would give you the expected result. Hopefully the ES6 support gets better soon. That would save you the explicit @type and @name tags. You should not put the tripple backticks around the example, because syntax highlighting for examples is always enabled.

Hope this helps!

**Comment by trusktr** [comment] 2016-05-17 08:58
Oops! I was not sure what to expect. I thought perhaps it would output
plain text including the backticks or HTML from markdown.

On Tuesday, May 17, 2016, Gerhard Preuss <notifications@github.com> wrote:

> @trusktr <https://github.com/trusktr> The problem is mainly that JSDoc
> (which is used internally) has some difficulties to deduce proper types and
> names for ES6.
>
> For instance:
>
> /**
>  * Await for a certain amount of time.
>  *
>  * @example
>  * ```js
>  * async function main() {
>  *     await sleep(10000)
>  *     console.log('Logged after 10000 milliseconds!')
>  * }
>  * main()
>  * ```
>  */
> export default
> function sleep(duration) {
>
> from https://github.com/trusktr/awaitbox/blob/master/src/timers/sleep.js
>
> should be
>
> /** * Await for a certain amount of time. * @name sleep * @type function * @param {number} duration The time in ms to sleep * @returns {Promise} A promise which gets resolved after `duration` has expired. * @example * async function main() { *     await sleep(10000) *     console.log('Logged after 10000 milliseconds!') * } * main() */export defaultfunction sleep(duration) {
>
> This would give you the expected result. Hopefully the ES6 support gets
> better soon. That would save you the explicit @type
> <https://github.com/type> and @name <https://github.com/name> tags. You
> should not put the tripple backticks around the example, because syntax
> highlighting for examples is always enabled.
>
> Hope this helps!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/lipp/doclets/issues/123#issuecomment-219635955>
>


-- 
/#!/JoePea

**Comment by lipp** [comment] 2016-05-18 18:23
Can I close this?

**Comment by trusktr** [comment] 2016-05-19 23:36
@lipp Yeah :)

**Closed** 2016-05-21 08:00 UTC
