### ISSUE TITLE
snyc error

### ISSUE THREAD

**Issue by joscha** [lipp/doclets#56] opened 2016-02-29 00:41 UTC
Hitting https://doclets.io/sync shows:
```
Err {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}
```
I believe that happened, because of the following steps:
* Login to doclets.io, granting access
* Revoking the access for doclets.io on the github side (I did that because organization repos weren't showing up before knowing it was due to #50)
* Logging in to doclets.io again, granting access again
* Clicking the `Re-Sync Repositories` button.

**Comment by lipp** [comment] 2016-02-29 07:37
thanks for reporting! sorry for the trouble. there is no work around yet...
working on this.

**Comment by lipp** [comment] 2016-02-29 07:37
this is a duplicate of #47

**Closed by lipp** 2016-02-29 07:37 UTC
